config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'locations#index'
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/download.rb
class Download < ApplicationRecord
  geocoded_by :ip
  after_validation :geocode
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address       # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  searchkick locations: [:location]

  def address
    [street, city, zip, state].compact.join(", ")
  end

  def address_changed?
    street_changed? || city_changed? || zip_changed? || state_changed?
  end

  def search_data
    attributes.merge location: { lat: latitude, lon: longitude }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(allowed_params)
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(allowed_params)
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_url, :notice => "Successfully destroyed location."
  end

  private

  def allowed_params
    params.require(:location).permit(:id, :address, :latitude, :longitude)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:street, :city, :zip, :state, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapsRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class='container' id="container">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
<p>
  <%= f.label :address %><br />
  <%= f.text_field :address %>
</p>
<p>
  <%= f.label :latitude %><br />
  <%= f.text_field :latitude %>
</p>
<p>
  <%= f.label :longitude %><br />
  <%= f.text_field :longitude %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>
<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<%= form_tag locations_path, :method => :get do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search Near", :name => nil %>
</p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
  <tr>
    <td>
      <%= location.address %>
    </td>
    <td>
      <%= location.latitude %>
    </td>
    <td>
      <%= location.longitude %>
    </td>
    <td>
      <%= link_to "Show", location %>
    </td>
    <td>
      <%= link_to "Edit", edit_location_path(location) %>
    </td>
    <td>
      <%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
  <% end %>
</table>

<p>
  <%= link_to "New Location", new_location_path %>
</p>

app/views/locations/new.html.erb
<%= render 'form' %>
<p>
  <%= link_to "Back to List", locations_path %>
</p>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<h3>Nearby locations</h3>
<ul>
  <% for location in @location.nearbys(10) %>
  <li>
    <%= link_to location.address, location %> (
    <%= location.distance.round(2) %> miles)</li>
  <% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, id: :transaction_street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :transaction_city %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :transaction_zip %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :transaction_state %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :transaction_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :transaction_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>Zip</th>
      <th>State</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.street %></td>
        <td><%= transaction.city %></td>
        <td><%= transaction.zip %></td>
        <td><%= transaction.state %></td>
        <td><%= transaction.latitude %></td>
        <td><%= transaction.longitude %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @transaction.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @transaction.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @transaction.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @transaction.state %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @transaction.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @transaction.longitude %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>